# environment variables first, then config file

is_debug = true

# Superuser is the first user of the system, who has all the permissions
# `username` "admin" is reserved for superuser.
# `email` property is invalid for superuser. In fact it's "admin@mails.tsinghua.edu.cn"
# It supports hot reload, so you can change the following values at any time
[superuser]
password = "password"

[db]
host = "localhost"
port = 3306
name = "dbname"
user = "user"
password = "password"

[redis]
host = "localhost"
port = 6379
password = "password"
db = 0
