# environment variables first, then config file

is_debug = true

# Superadmin is the first user of the system, who has all the permissions
# `username` "admin" is reserved for superadmin.
# `email` property is invalid for superadmin. In fact it's "admin@mails.tsinghua.edu.cn"
# It supports hot reload, so you can change the following values at any time
[superadmin]
password = "password"

[db]
host = "localhost"
port = 5432
user = "hiper"
password = "hiper"
dbname = "hiper"

[redis]
host = "localhost"
port = 6379
password = ""
db = 0

[mail]
host = "smtp.qq.com"
port = 465
username = "1585525821@qq.com"
password = "rhlccveuamqxicbg"
